services:
  - type: web
    name: webrandom
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: daphne WebRandom.asgi:application --port $PORT --bind 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com" 