# Generated by Django 5.1.7 on 2025-03-11 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_builds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('github_username', models.CharField(max_length=100)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
