import random

def generate_clash_royale_build():
    cards = [
        {"name": "Knight", "image": "/static/images/ClashRoyale/Knight.png", "rarity": "Common"},
        {"name": "Archers", "image": "/static/images/ClashRoyale/Archers.png", "rarity": "Common"},
        {"name": "Goblins", "image": "/static/images/ClashRoyale/Goblins.png", "rarity": "Common"},
        {"name": "Spear Goblins", "image": "/static/images/ClashRoyale/SpearGoblins.png", "rarity": "Common"},
        {"name": "Minions", "image": "/static/images/ClashRoyale/Minions.png", "rarity": "Common"},
        {"name": "Skeleton Barrel", "image": "/static/images/ClashRoyale/SkeletonBarrel.png", "rarity": "Common"},
        {"name": "Skeletons", "image": "/static/images/ClashRoyale/Skeletons.png", "rarity": "Common"},
        {"name": "Bomber", "image": "/static/images/ClashRoyale/Bomber.png", "rarity": "Common"},
        {"name": "Bats", "image": "/static/images/ClashRoyale/Bats.png", "rarity": "Common"},
        {"name": "Firecracker", "image": "/static/images/ClashRoyale/Firecracker.png", "rarity": "Common"},
        {"name": "Royal Delivery", "image": "/static/images/ClashRoyale/RoyalDelivery.png", "rarity": "Common"},
        {"name": "Tesla", "image": "/static/images/ClashRoyale/Tesla.png", "rarity": "Common"},
        {"name": "Zap", "image": "/static/images/ClashRoyale/Zap.png", "rarity": "Common"},
        {"name": "Arrows", "image": "/static/images/ClashRoyale/Arrows.png", "rarity": "Common"},
        {"name": "Barbarians", "image": "/static/images/ClashRoyale/Barbarians.png", "rarity": "Common"},
        {"name": "Royal Recruits", "image": "/static/images/ClashRoyale/RoyalRecruits.png", "rarity": "Common"},
        {"name": "Cannon", "image": "/static/images/ClashRoyale/Cannon.png", "rarity": "Common"},
        {"name": "Mortar", "image": "/static/images/ClashRoyale/Mortar.png", "rarity": "Common"},
        {"name": "Royal Giant", "image": "/static/images/ClashRoyale/RoyalGiant.png", "rarity": "Common"},
        {"name": "Elite Barbarians", "image": "/static/images/ClashRoyale/EliteBarbarians.png", "rarity": "Common"},
        {"name": "Minion Horde", "image": "/static/images/ClashRoyale/MinionHorde.png", "rarity": "Common"},
        {"name": "Ice Spirit", "image": "/static/images/ClashRoyale/IceSpirit.png", "rarity": "Common"},
        {"name": "Fire Spirit", "image": "/static/images/ClashRoyale/FireSpirit.png", "rarity": "Common"},
        {"name": "Electro Spirit", "image": "/static/images/ClashRoyale/ElectroSpirit.png", "rarity": "Common"},
        {"name": "Goblin Gang", "image": "/static/images/ClashRoyale/GoblinGang.png", "rarity": "Common"},
        {"name": "Skeleton Dragons", "image": "/static/images/ClashRoyale/SkeletonDragons.png", "rarity": "Common"},
        {"name": "Rascals", "image": "/static/images/ClashRoyale/Rascals.png", "rarity": "Common"},
        {"name": "Giant", "image": "/static/images/ClashRoyale/Giant.png", "rarity": "Rare"},
        {"name": "Goblin Cage", "image": "/static/images/ClashRoyale/GoblinCage.png", "rarity": "Rare"},
        {"name": "Goblin Hut", "image": "/static/images/ClashRoyale/GoblinHut.png", "rarity": "Rare"},
        {"name": "Furnace", "image": "/static/images/ClashRoyale/Furnace.png", "rarity": "Rare"},
        {"name": "Musketeer", "image": "/static/images/ClashRoyale/Musketeer.png", "rarity": "Rare"},
        {"name": "Valkyrie", "image": "/static/images/ClashRoyale/Valkyrie.png", "rarity": "Rare"},
        {"name": "Mini P.E.K.K.A", "image": "/static/images/ClashRoyale/MiniPEKKA.png", "rarity": "Rare"},
        {"name": "Hog Rider", "image": "/static/images/ClashRoyale/HogRider.png", "rarity": "Rare"},
        {"name": "Fireball", "image": "/static/images/ClashRoyale/Fireball.png", "rarity": "Rare"},
        {"name": "Rocket", "image": "/static/images/ClashRoyale/Rocket.png", "rarity": "Rare"},
        {"name": "Bomb Tower", "image": "/static/images/ClashRoyale/BombTower.png", "rarity": "Rare"},
        {"name": "Inferno Tower", "image": "/static/images/ClashRoyale/InfernoTower.png", "rarity": "Rare"},
        {"name": "Wizard", "image": "/static/images/ClashRoyale/Wizard.png", "rarity": "Rare"},
        {"name": "Flying Machine", "image": "/static/images/ClashRoyale/FlyingMachine.png", "rarity": "Rare"},
        {"name": "Zappies", "image": "/static/images/ClashRoyale/Zappies.png", "rarity": "Rare"},
        {"name": "Royal Hogs", "image": "/static/images/ClashRoyale/RoyalHogs.png", "rarity": "Rare"},
        {"name": "Barbarian Hut", "image": "/static/images/ClashRoyale/BarbarianHut.png", "rarity": "Rare"},
        {"name": "Elixir Collector", "image": "/static/images/ClashRoyale/ElixirCollector.png", "rarity": "Rare"},
        {"name": "Battle Ram", "image": "/static/images/ClashRoyale/BattleRam.png", "rarity": "Rare"},
        {"name": "Tombstone", "image": "/static/images/ClashRoyale/Tombstone.png", "rarity": "Rare"},
        {"name": "Dart Goblin", "image": "/static/images/ClashRoyale/DartGoblin.png", "rarity": "Rare"},
        {"name": "Mega Minion", "image": "/static/images/ClashRoyale/MegaMinion.png", "rarity": "Rare"},
        {"name": "Heal Spirit", "image": "/static/images/ClashRoyale/HealSpirit.png", "rarity": "Rare"},
        {"name": "Ice Golem", "image": "/static/images/ClashRoyale/IceGolem.png", "rarity": "Rare"},
        {"name": "Three Musketeers", "image": "/static/images/ClashRoyale/ThreeMusketeers.png", "rarity": "Rare"},
        {"name": "Earthquake", "image": "/static/images/ClashRoyale/Earthquake.png", "rarity": "Rare"},
        {"name": "Baby Dragon", "image": "/static/images/ClashRoyale/BabyDragon.png", "rarity": "Epic"},
        {"name": "P.E.K.K.A", "image": "/static/images/ClashRoyale/PEKKA.png", "rarity": "Epic"},
        {"name": "Balloon", "image": "/static/images/ClashRoyale/Balloon.png", "rarity": "Epic"},
        {"name": "Goblin Barrel", "image": "/static/images/ClashRoyale/GoblinBarrel.png", "rarity": "Epic"},
        {"name": "Skeleton Army", "image": "/static/images/ClashRoyale/SkeletonArmy.png", "rarity": "Epic"},
        {"name": "Witch", "image": "/static/images/ClashRoyale/Witch.png", "rarity": "Epic"},
        {"name": "Prince", "image": "/static/images/ClashRoyale/Prince.png", "rarity": "Epic"},
        {"name": "Dark Prince", "image": "/static/images/ClashRoyale/DarkPrince.png", "rarity": "Epic"},
        {"name": "Freeze", "image": "/static/images/ClashRoyale/Freeze.png", "rarity": "Epic"},
        {"name": "Poison", "image": "/static/images/ClashRoyale/Poison.png", "rarity": "Epic"},
        {"name": "Lightning", "image": "/static/images/ClashRoyale/Lightning.png", "rarity": "Epic"},
        {"name": "Tornado", "image": "/static/images/ClashRoyale/Tornado.png", "rarity": "Epic"},
        {"name": "Clone", "image": "/static/images/ClashRoyale/Clone.png", "rarity": "Epic"},
        {"name": "Mirror", "image": "/static/images/ClashRoyale/Mirror.png", "rarity": "Epic"},
        {"name": "Rage", "image": "/static/images/ClashRoyale/Rage.png", "rarity": "Epic"},
        {"name": "Golem", "image": "/static/images/ClashRoyale/Golem.png", "rarity": "Epic"},
        {"name": "Goblin Drill", "image": "/static/images/ClashRoyale/GoblinDrill.png", "rarity": "Epic"},
        {"name": "Goblin Giant", "image": "/static/images/ClashRoyale/GoblinGiant.png", "rarity": "Epic"},
        {"name": "Electro Giant", "image": "/static/images/ClashRoyale/ElectroGiant.png", "rarity": "Epic"},
        {"name": "Barbarian Barrel", "image": "/static/images/ClashRoyale/BarbarianBarrel.png", "rarity": "Epic"},
        {"name": "Wall Breakers", "image": "/static/images/ClashRoyale/WallBreakers.png", "rarity": "Epic"},
        {"name": "Hunter", "image": "/static/images/ClashRoyale/Hunter.png", "rarity": "Epic"},
        {"name": "Executioner", "image": "/static/images/ClashRoyale/Executioner.png", "rarity": "Epic"},
        {"name": "Bowler", "image": "/static/images/ClashRoyale/Bowler.png", "rarity": "Epic"},
        {"name": "X-Bow", "image": "/static/images/ClashRoyale/XBow.png", "rarity": "Epic"},
        {"name": "Giant Skeleton", "image": "/static/images/ClashRoyale/GiantSkeleton.png", "rarity": "Epic"},
        {"name": "Electro Dragon", "image": "/static/images/ClashRoyale/ElectroDragon.png", "rarity": "Epic"},
        {"name": "Lava Hound", "image": "/static/images/ClashRoyale/LavaHound.png", "rarity": "Legendary"},
        {"name": "Miner", "image": "/static/images/ClashRoyale/Miner.png", "rarity": "Legendary"},
        {"name": "Princess", "image": "/static/images/ClashRoyale/Princess.png", "rarity": "Legendary"},
        {"name": "Ice Wizard", "image": "/static/images/ClashRoyale/IceWizard.png", "rarity": "Legendary"},
        {"name": "Night Witch", "image": "/static/images/ClashRoyale/NightWitch.png", "rarity": "Legendary"},
        {"name": "Electro Wizard", "image": "/static/images/ClashRoyale/ElectroWizard.png", "rarity": "Legendary"},
        {"name": "Inferno Dragon", "image": "/static/images/ClashRoyale/InfernoDragon.png", "rarity": "Legendary"},
        {"name": "Lumberjack", "image": "/static/images/ClashRoyale/Lumberjack.png", "rarity": "Legendary"},
        {"name": "Sparky", "image": "/static/images/ClashRoyale/Sparky.png", "rarity": "Legendary"},
        {"name": "The Log", "image": "/static/images/ClashRoyale/TheLog.png", "rarity": "Legendary"},
        {"name": "Magic Archer", "image": "/static/images/ClashRoyale/MagicArcher.png", "rarity": "Legendary"},
        {"name": "Mother Witch", "image": "/static/images/ClashRoyale/MotherWitch.png", "rarity": "Legendary"},
        {"name": "Ram Rider", "image": "/static/images/ClashRoyale/RamRider.png", "rarity": "Legendary"},
        {"name": "Mega Knight", "image": "/static/images/ClashRoyale/MegaKnight.png", "rarity": "Legendary"},
        {"name": "Fisherman", "image": "/static/images/ClashRoyale/Fisherman.png", "rarity": "Legendary"},
        {"name": "Bandit", "image": "/static/images/ClashRoyale/Bandit.png", "rarity": "Legendary"},
        {"name": "Royal Ghost", "image": "/static/images/ClashRoyale/RoyalGhost.png", "rarity": "Legendary"},
        {"name": "Phoenix", "image": "/static/images/ClashRoyale/Phoenix.png", "rarity": "Legendary"},
        {"name": "Golden Knight", "image": "/static/images/ClashRoyale/GoldenKnight.png", "rarity": "Champion"},
        {"name": "Skeleton King", "image": "/static/images/ClashRoyale/SkeletonKing.png", "rarity": "Champion"},
        {"name": "Archer Queen", "image": "/static/images/ClashRoyale/ArcherQueen.png", "rarity": "Champion"},
        {"name": "Mighty Miner", "image": "/static/images/ClashRoyale/MightyMiner.png", "rarity": "Champion"},
        {"name": "Monk", "image": "/static/images/ClashRoyale/Monk.png", "rarity": "Champion"},
        {"name": "Little Prince", "image": "/static/images/ClashRoyale/LittlePrince.png", "rarity": "Champion"},
        {"name": "Rune Giant", "image": "/static/images/ClashRoyale/RuneGiant.png", "rarity": "Epic"},
        {"name": "Berserker", "image": "/static/images/ClashRoyale/Berserker.png", "rarity": "Common"},
        {"name": "Boss Bandit", "image": "/static/images/ClashRoyale/BossBandit.png", "rarity": "Champion"},
        {"name": "Giant Snowball", "image": "/static/images/ClashRoyale/GiantSnowball.png", "rarity": "Common"},
        {"name": "Goblinstein", "image": "/static/images/ClashRoyale/Goblinstein.png", "rarity": "Champion"},
        {"name": "Suspicious Bush", "image": "/static/images/ClashRoyale/SuspiciousBush.png", "rarity": "Rare"},
        {"name": "Elixir Golem", "image": "/static/images/ClashRoyale/ElixirGolem.png", "rarity": "Rare"},
        {"name": "Battle Healer", "image": "/static/images/ClashRoyale/BattleHealer.png", "rarity": "Rare"},
        {"name": "Guards", "image": "/static/images/ClashRoyale/Guards.png", "rarity": "Epic"},
        {"name": "Void", "image": "/static/images/ClashRoyale/Void.png", "rarity": "Epic"},
        {"name": "Cannon Cart", "image": "/static/images/ClashRoyale/CannonCart.png", "rarity": "Epic"},
        {"name": "Graveyard", "image": "/static/images/ClashRoyale/Graveyard.png", "rarity": "Legendary"},
        {"name": "Goblin Demolisher", "image": "/static/images/ClashRoyale/GoblinDemolisher.png", "rarity": "Rare"},
        {"name": "Goblin Curse", "image": "/static/images/ClashRoyale/GoblinCurse.png", "rarity": "Epic"},
        {"name": "Goblin Machine", "image": "/static/images/ClashRoyale/GoblinMachine.png", "rarity": "Legendary"},
    ]

    deck = random.sample(cards, 8)

    return {
        "deck": deck
    }