import random

def generate_dead_by_daylight_build():
    roles = {
        "survivor": ["Dwight Fairfield", "Meg Thomas", "Claudette Morel", "Jake Park", "Nea Karlsson", "Laurie Strode", "Ace Visconti", "Bill Overbeck", "Feng Min", "David King", "Quentin Smith", "David Tapp", "Kate Denson", "Adam Francis", "Jeff Johansen", "Jane Romero", "Ash Williams", "Nancy Wheeler", "Steve Harrington", "Yui Kimura", "Zarina Kassir", "Cheryl Mason", "Felix Richter", "Elodie Rakoto", "Yun-Jin Lee", "Leon Scott Kennedy", "Jill Valentine", "Mikaela Reid", "Jonah Vasquez", "Yoichi Asakawa", "Haddie Kaur", "Ada Wong", "Rebecca Chambers", "Vittorio Toscano", "Thalita Lyra", "Renato Lyra", "Gabriel Soma", "Nicolas Cage", "Ellen Ripley", "Alan Wake", "Sable Ward", "Aestri Yazar & Baermar Uraz", "Lara Croft", "Trevor Belmont", "Taurie Cain"],
        "killer": ["The Trapper", "The Wraith", "The Hillbilly", "The Nurse", "The Shape", "The Hag", "The Doctor", "The Huntress", "The Cannibal", "The Nightmare", "The Pig", "The Clown", "The Spirit", "The Legion", "The Plague", "The Ghost Face", "The Demogorgon", "The Oni", "The Deathslinger", "The Executioner", "The Blight", "The Twins", "The Trickster", "The Nemesis", "The Cenobite", "The Artist", "The Onryo", "The Dredge", "The Mastermind", "The Knight", "The Skull Merchant", "The Singularity", "The Xenomorph", "The Good Guy", "The Unknown", "The Lich", "The Dark Lord", "The Houndmaster"]
    }

    survivor_perks = ["Adrenaline", "Aftercare", "Alert", "Any Means Necessary", "Appraisal", "Autodidact", "Babysitter", "Background Player", "Balanced Landing", "Bang!", "Bardic Inspiration", "Better Than New", "Bite the Bullet", "Blast Mine", "Blood Pact", "Blood Rush", "Boil Over", "Bond", "Boon: Circle of Healing", "Boon: Dark Theory", "Boon: Exponential", "Boon: Illumination", "Boon: Shadow Step", "Botany Knowledge", "Breakdown", "Breakout", "Buckle Up", "Built to Last", "Calm Spirit", "Champion of Light", "Chemical Trap", "Clairvoyance", "Collective Stealth", "Corrective Action", "Counterforce", "Cut Loose", "Dance With Me", "Dark Sense", "Dead Hard", "Deception", "Decisive Strike", "Déjà Vu", "Deliverance", "Desperate Measures", "Distortion", "Diversion", "Dramaturgy", "Empathic Connection", "Empathy", "Escape Artist", "Exultation", "Fast Track", "Finesse", "Fixated", "Flashbang", "Flip-Flop", "Fogwise", "For the People", "Friendly Competition", "Guardian", "Hardened", "Head On", "Hope", "Hunch", "Hyperfocus", "Inner Healing", "Inner Strength", "Iron Will", "Kindred", "Kinship", "Last Standing", "Leader", "Left Behind", "Light-Footed", "Lightweight", "Lithe", "Low Profile", "Lucky Break", "Lucky Star", "Made for This", "Mettle of Man", "No Mither", "No One Left Behind", "Object of Obsession", "Off the Record", "Open-Handed", "Overcome", "Overzealous", "Parental Guidance", "Pharmacy", "Plunderer's Instinct", "Poised", "Potential Energy", "Power Struggle", "Premonition", "Prove Thyself", "Quick & Quiet", "Reactive Healing", "Red Herring", "Renewal", "Repressed Alliance", "Resilience", "Resurgence", "Rookie Spirit", "Saboteur", "Scene Partner", "Second Wind", "Self-Aware", "Self-Care", "Self-Preservation", "Situational Awareness", "Slippery Meat", "Small Game", "Smash Hit", "Sole Survivor", "Solidarity", "Soul Guard", "Specialist", "Spine Chill", "Sprint Burst", "Stake Out", "Streetwise", "Strength in Shadows", "Survivor Puddles", "Teamwork: Collective Stealth", "Teamwork: Power of Two", "Technician", "Tenacity", "This Is Not Happening", "Troubleshooter", "Unbreakable", "Up the Ante", "Urban Evasion", "Vigil", "Visionary", "Wake Up!", "We'll Make It", "We're Gonna Live Forever", "Wicked", "Windows of Opportunity", "Wiretap"]
    killer_perks = ["Agitation", "Alien Instinct", "All-Shaking Thunder", "Awakened Awareness", "Bamboozle", "Barbecue & Chilli", "Batteries Included", "Beast of Prey", "Bitter Murmur", "Blood Echo", "Blood Warden", "Bloodhound", "Brutal Strength", "Call of Brine", "Claustrophobia", "Corrupt Intervention", "Coulrophobia", "Coup de Grâce", "Cruel Limits", "Dark Arrogance", "Dark Devotion", "Darkness Revealed", "Dead Man's Switch", "Deadlock", "Deathbound", "Deerstalker", "Discordance", "Dissolution", "Distressing", "Dominance", "Dragon's Grip", "Dying Light", "Enduring", "Eruption", "Fearmonger", "Fire Up", "Forced Hesitation", "Forced Penance", "Franklin's Demise", "Friends 'til the End", "Furtive Chase", "Game Afoot", "Gearhead", "Grim Embrace", "Hangman's Trick", "Hex: Blood Favour", "Hex: Crowd Control", "Hex: Devour Hope", "Hex: Face the Darkness", "Hex: Haunted Ground", "Hex: Huntress Lullaby", "Hex: No One Escapes Death", "Hex: Pentimento", "Hex: Plaything", "Hex: Retribution", "Hex: Ruin", "Hex: The Third Seal", "Hex: Thrill of the Hunt", "Hex: Undying", "Hoarder", "Hooked on You", "Hysteria", "I'm All Ears", "Infectious Fright", "Insidious", "Iron Grasp", "Iron Maiden", "Jolt", "Knock Out", "Languid Touch", "Lethal Pursuer", "Leverage", "Lightborn", "Machine Learning", "Mad Grit", "Make Your Choice", "Mindbreaker", "Monitor & Abuse", "Monstrous Shrine", "Nemesis", "No Quarter", "No Way Out", "Nowhere to Hide", "Oppression", "Overcharge", "Overwhelming Presence", "Pain Resonance", "Play With Your Food", "Pop Goes the Weasel", "Predator", "Rancor", "Rapid Brutality", "Remember Me", "Repressed Fear", "Save the Best for Last", "Scourge Hook: Floods of Rage", "Scourge Hook: Gift of Pain", "Scourge Hook: Monstrous Shrine", "Scourge Hook: Pain Resonance", "Septic Touch", "Shadowborn", "Sloppy Butcher", "Spies from the Shadows", "Spirit Fury", "Starstruck", "Stridor", "Superior Anatomy", "Surge", "Surveillance", "Territorial Imperative", "Thanatophobia", "Thrilling Tremors", "Tinkerer", "Trail of Torment", "Unbound", "Undone", "Unforeseen", "Unnerving Presence", "Unrelenting", "Ultimate Weapon", "Weave Attunement", "Whispers", "Zanshin Tactics"]

    role = random.choice(list(roles.keys()))
    character = random.choice(roles[role])

    character_image = f"/static/images/DeadByDaylight/{role.capitalize()}s/{character.replace(' ', '')}.png"

    perks = random.sample(survivor_perks, 4) if role == "survivor" else random.sample(killer_perks, 4)

    items = ["Medkit", "Flashlight", "Toolbox", "Map", "Key"] if role == "survivor" else []

    build = {
        "role": role,
        "character": character,
        "character_image_png": character_image,
        "perks": perks,
        "item": random.choice(items) if items else None
    }

    return build